import React, { useRef } from 'react';
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import Card from "@mui/material/Card";
import CardContent from "@mui/material/CardContent";
import Stack from "@mui/material/Stack";
import Typography from "@mui/material/Typography";
import { BarChart } from "@mui/x-charts/BarChart";
import { PieChart } from "@mui/x-charts/PieChart";
import { Gauge } from "@mui/x-charts/Gauge";
import { DataGrid } from '@mui/x-data-grid';

const columns = [
  { field: 'id', headerName: 'ID', width: 90 },
  { field: 'firstName', headerName: 'First name', width: 150 },
  { field: 'lastName', headerName: 'Last name', width: 150 },
  { field: 'age', headerName: 'Age', type: 'number', width: 110 },
  { 
    field: 'fullName', 
    headerName: 'Full name', 
    sortable: false, 
    width: 200, 
    valueGetter: (_, row) => `${row.firstName || ''} ${row.lastName || ''}`,
  },
];

const rows = [
  { id: 1, lastName: 'Swift', firstName: 'Taylor', age: 34, status: 'Active Tour' },
  { id: 2, lastName: 'Grande', firstName: 'Ariana', age: 30, status: 'Recording' },
  { id: 3, lastName: 'Knowles', firstName: 'Beyoncé', age: 42, status: 'Hiatus' },
  { id: 4, lastName: 'Gaga', firstName: 'Lady', age: 38, status: 'Active Tour' },
  { id: 5, lastName: 'Mars', firstName: 'Bruno', age: 38, status: 'Active Tour' },
];

const ReportsPage = () => {
  const printRef = useRef(null);

  const handlePrint = () => {
    const printContent = printRef.current;
    if (!printContent) return;

    const printWindow = window.open('', '_blank', 'width=1200,height=900');
    if (!printWindow) return;

    // Grab MUI styles to ensure the charts look good in print
    const headMarkup = Array.from(document.querySelectorAll('style, link[rel="stylesheet"]'))
      .map((node) => node.outerHTML)
      .join('');

    const exportedAt = new Intl.DateTimeFormat('en-US', {
      dateStyle: 'long',
      timeStyle: 'short',
    }).format(new Date());

    // Create a detailed table for the printout
    const tableRowsHtml = rows.map(r => `
      <tr>
        <td style="padding: 10px; border-bottom: 1px solid #ddd;">${r.id}</td>
        <td style="padding: 10px; border-bottom: 1px solid #ddd;"><b>${r.firstName} ${r.lastName}</b></td>
        <td style="padding: 10px; border-bottom: 1px solid #ddd;">${r.age}</td>
        <td style="padding: 10px; border-bottom: 1px solid #ddd;">${r.status}</td>
      </tr>
    `).join('');

    printWindow.document.write(`
      <!DOCTYPE html>
      <html lang="en">
        <head>
          <meta charset="UTF-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <title>Detailed Print Report</title>
          ${headMarkup}
          <style>
            @page { size: A4; margin: 20mm; }
            * { box-sizing: border-box; }
            body { margin: 0; font-family: 'Helvetica Neue', Arial, sans-serif; background: #fff; color: #1f2937; }
            .report-shell { padding: 0px; }
            .report-header { margin-bottom: 30px; padding-bottom: 20px; border-bottom: 2px solid #aa3bff; }
            .report-header h1 { margin: 0 0 10px; font-size: 32px; font-weight: 800; color: #aa3bff; text-transform: uppercase; letter-spacing: 1px;}
            .report-header p { margin: 0 0 5px; font-size: 14px; color: #6b7280; }
            .summary-stats { display: flex; gap: 20px; margin-bottom: 30px; }
            .stat-box { background: #f9f9f9; padding: 15px 20px; border-radius: 8px; flex: 1; border-left: 4px solid #aa3bff; }
            .stat-box span { display: block; font-size: 12px; color: #6b7280; text-transform: uppercase; font-weight: bold; }
            .stat-box strong { font-size: 24px; color: #1f2937; }
            .report-content .MuiCard-root { box-shadow: none !important; border: 1px solid #e5e7eb; break-inside: avoid; page-break-inside: avoid; margin-bottom: 20px;}
            .report-content svg { max-width: 100%; }
            .data-table { width: 100%; border-collapse: collapse; margin-top: 30px; font-size: 14px; break-inside: avoid; }
            .data-table th { background-color: #aa3bff; color: white; text-align: left; padding: 12px 10px; }
          </style>
        </head>
        <body>
          <main class="report-shell">
            <header class="report-header">
              <h1>Executive Summary Report</h1>
              <p><b>Generated By:</b> System Administrator</p>
              <p><b>Date:</b> ${exportedAt}</p>
            </header>

            <div class="summary-stats">
              <div class="stat-box"><span>Total Audio Streams</span><strong>1.6 Billion</strong></div>
              <div class="stat-box"><span>Physical Sales</span><strong>1.45 Million</strong></div>
              <div class="stat-box"><span>Active Tours</span><strong>3</strong></div>
            </div>

            <section class="report-content">
              ${printContent.outerHTML}
            </section>

            <table class="data-table">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Artist Name</th>
                  <th>Age</th>
                  <th>Current Status</th>
                </tr>
              </thead>
              <tbody>
                ${tableRowsHtml}
              </tbody>
            </table>
          </main>
        </body>
      </html>
    `);

    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => { printWindow.print(); }, 800); 
  };

  return (
    <Box>
      <Stack direction={{ xs: "column", md: "row" }} justifyContent="space-between" alignItems={{ xs: "flex-start", md: "center" }} spacing={2} sx={{ mb: 4 }}>
        <Box>
          <Typography variant="h4" sx={{ fontWeight: 'bold', color: '#aa3bff' }} gutterBottom>Reports</Typography>
          <Typography variant="body1" color="text.secondary">
            Analytics overview for streams, sales, and platform performance.
          </Typography>
        </Box>

        <Stack direction="row" spacing={1.5} flexWrap="wrap" useFlexGap>
          <Button variant="contained" sx={{ backgroundColor: '#aa3bff', '&:hover': { backgroundColor: '#8a2be2' }}}>Generate</Button>
          <Button variant="outlined" sx={{ color: '#aa3bff', borderColor: '#aa3bff'}} onClick={handlePrint}>Export PDF</Button>
        </Stack>
      </Stack>

      <Stack ref={printRef} spacing={3}>
        <Card sx={{ borderRadius: '15px', boxShadow: '0 4px 10px rgba(0,0,0,0.05)' }}>
          <CardContent>
            <Typography variant="h6" gutterBottom>Quarterly Streams vs Sales (Millions)</Typography>
            <BarChart
              series={[
                { data: [350, 450, 250, 550], label: "Streams", color: '#aa3bff' },
                { data: [500, 150, 500, 300], label: "Physical Sales", color: '#FFD700' },
              ]}
              height={300}
              xAxis={[{ data: ["Q1", "Q2", "Q3", "Q4"], scaleType: "band" }]}
            />
          </CardContent>
        </Card>

        <Stack direction={{ xs: "column", lg: "row" }} spacing={3}>
          <Card sx={{ flex: 1, borderRadius: '15px', boxShadow: '0 4px 10px rgba(0,0,0,0.05)' }}>
            <CardContent>
              <Typography variant="h6" gutterBottom>Genre Distribution</Typography>
              <Box sx={{ display: "flex", justifyContent: "center" }}>
                <PieChart
                  series={[{
                      data: [
                        { id: 0, value: 45, label: "Pop", color: '#aa3bff' },
                        { id: 1, value: 25, label: "R&B", color: '#e91e63' },
                        { id: 2, value: 30, label: "Country", color: '#FFD700' },
                      ],
                  }]}
                  width={300}
                  height={220}
                />
              </Box>
            </CardContent>
          </Card>

          <Card sx={{ flex: 1, borderRadius: '15px', boxShadow: '0 4px 10px rgba(0,0,0,0.05)' }}>
            <CardContent>
              <Typography variant="h6" gutterBottom>Tour Completion Rate</Typography>
              <Box sx={{ minHeight: 220, display: "flex", alignItems: "center", justifyContent: "center" }}>
                <Gauge width={180} height={180} value={85} />
              </Box>
            </CardContent>
          </Card>
        </Stack>

        {/* Hide DataGrid from print since we render a custom HTML table for it above */}
        <Box className="no-print">
          <Card sx={{ borderRadius: '15px', boxShadow: '0 4px 10px rgba(0,0,0,0.05)' }}>
            <CardContent>
              <Typography variant="h6" gutterBottom sx={{ mb: 2 }}>Top Performers</Typography>
              <DataGrid
                rows={rows}
                columns={columns}
                initialState={{ pagination: { paginationModel: { pageSize: 5 } } }}
                pageSizeOptions={[5]}
                sx={{ border: 'none', '& .MuiDataGrid-columnHeaders': { backgroundColor: '#f4f3ec' } }}
              />
            </CardContent>
          </Card>
        </Box>
      </Stack>
    </Box>
  );
};

export default ReportsPage;